// <auto-generated />
namespace Cotillo_ShoppingCart_Services.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Additional_Update_05_11_2016 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Additional_Update_05_11_2016));
        
        string IMigrationMetadata.Id
        {
            get { return "201605111554423_Additional_Update_05_11_2016"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
