// <auto-generated />
namespace Cotillo_ShoppingCart_Services.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TableUpdate_050516 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TableUpdate_050516));
        
        string IMigrationMetadata.Id
        {
            get { return "201605051848420_TableUpdate_050516"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
